### ISSUE TITLE
App crashes while loading metadata - IntroActivity

### ISSUE THREAD

**Issue by YasinAflatoon** [MahdiDavoodi/Sievere#14]
App has crash in intro section.

> Device: Galaxy A750
> Android: 10

**Comment by MahdiDavoodi** [comment]
## Log

```java
E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: davoodi.mahdi.sievere, PID: 19876
    java.lang.RuntimeException: setDataSource failed: status = 0x80000000
        at android.media.MediaMetadataRetriever.setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:151)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:199)
        at davoodi.mahdi.sievere.tools.Utilities$Companion.getAlbumArt(Utilities.kt:13)
        at davoodi.mahdi.sievere.components.Album.<init>(Album.kt:12)
        at davoodi.mahdi.sievere.data.DataLoader.updateAlbums(DataLoader.kt:74)
        at davoodi.mahdi.sievere.data.DataLoader.loadData(DataLoader.kt:110)
        at davoodi.mahdi.sievere.activities.IntroActivity.lambda$loadData$0$davoodi-mahdi-sievere-activities-IntroActivity(IntroActivity.java:36)
        at davoodi.mahdi.sievere.activities.IntroActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)
```

## Description

There is an unknown problem with MediaMetadataRetriever. Apparently, it receives a null value at some point, which causes the crash.
